name: DevOps ITIS Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Controllo Sintassi Base
        run: echo "Controllo qualità superato con la nuova cartella assets!"

  container-registry:
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Login al GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push dell'immagine Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/bianca-t40/progettositoweb/test-sito:latest

  deployment:
    runs-on: ubuntu-latest
    needs: container-registry
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v4

      - name: Carica i file statici
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
